### ISSUE TITLE
Issues adding guards

### ISSUE THREAD

**Issue by TheRizzock** [cryptorrivem/ts-sugar#1]
Trying to add a set of guards to the config file, but I keep having errors when doing so

```
$ ts-sugar guard add
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
/home/usr/Documents/ts-sugar/dist/storage/config.js:426
    var groups = guards.groups.map(function (_a) {
                               ^

TypeError: Cannot read properties of undefined (reading 'map')
    at readConfig (/home/usr/Documents/ts-sugar/dist/storage/config.js:426:32)
    at Command.<anonymous> (/home/usr/Documents/ts-sugar/dist/commands/guard.js:56:59)
    at step (/home/usr/Documents/ts-sugar/dist/commands/guard.js:33:23)
    at Object.next (/home/usr/Documents/ts-sugar/dist/commands/guard.js:14:53)
    at /home/usr/Documents/ts-sugar/dist/commands/guard.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/usr/Documents/ts-sugar/dist/commands/guard.js:4:12)
    at Command.guardAdd (/home/usr/Documents/ts-sugar/dist/commands/guard.js:48:12)
    at Command.listener [as _actionHandler] (/home/usr/Documents/ts-sugar/node_modules/.pnpm/commander@12.0.0/node_modules/commander/lib/command.js:523:17)
    at /home/dan/Documents/ts-sugar/node_modules/.pnpm/commander@12.0.0/node_modules/commander/lib/command.js:1375:65

Node.js v20.16.0
```

Not sure if this is a bug, or if this is because I also faced a error during build

```
$ pnpm build

> ts-sugar@1.0.0 build /home/usr/Documents/ts-sugar
> tsc src/ts-sugar.ts --lib dom,ESNext --outDir dist

node_modules/.pnpm/@metaplex-foundation+mpl-core@1.0.2_@metaplex-foundation+umi@0.9.1_@noble+hashes@1.4.0/node_modules/@metaplex-foundation/mpl-core/dist/src/plugins/externalPluginAdapterManifest.d.ts:1:40 - error TS2307: Cannot find module 'src/generated' or its corresponding type declarations.

1 import { ExternalRegistryRecord } from 'src/generated';
                                         ~~~~~~~~~~~~~~~


Found 1 error in node_modules/.pnpm/@metaplex-foundation+mpl-core@1.0.2_@metaplex-foundation+umi@0.9.1_@noble+hashes@1.4.0/node_modules/@metaplex-foundation/mpl-core/dist/src/plugins/externalPluginAdapterManifest.d.ts:1

 ELIFECYCLE  Command failed with exit code 2.
```
Within the config.json, the guards look like this. Note that I did first create the candy machine, then attempted to update the config and apply the guards

```
"guards": {
    "public":{
      "mintLimit":{
  	"id":1,
	"limit":10
	},
       "solPayment":{
         "value":0.01,
         "destination":"PUBLICKEY"
       },
       "startDate":{
         "date":"2024-09-03T02:30:00Z"
       },
       "botTax":{
       	"value":0.007,
       	"lastInstruction": true
       }
    }
  },
```

**Comment by TheRizzock** [comment]
Found the issue, need to assign a guard group and can't just set default like in sugar

**Comment by cryptorrivem** [comment]
sorry for the late reply, was gonna say that import error is due to an outdated dependency on mpl-core, fixing now

**Comment by cryptorrivem** [comment]
should now be fixed with
https://github.com/cryptorrivem/ts-sugar/commit/c12108898aafc91aae8c07353116bcf16d5178de

**Comment by endresol** [comment]
Hello.

I also get this error, even if I think I have the latest version.
Any ideas how to solve this?

**Comment by cryptorrivem** [comment]
hey @endresol which of the two errors from above you getting?

the build error shouldn't be present anymore with latest from `master`

I just did some maintenance and upgraded packages, try pulling the latest, installing dependencies and build to see if you still getting the issue
